### ISSUE TITLE
[Docs]: Make the side bar letters color to white

### ISSUE THREAD

**Issue by edsondsouza** [FrancescoXX/free-Web3-resources#456]
### Description

When the website is opened in dark mode, the titles on the right sidebar are in dark mode. It is difficult to view. It would be better if the color of the sidebar's contents were white.

### Anything else?

![image](https://user-images.githubusercontent.com/93525771/230701273-1039c879-c1ba-4fc9-ae34-ea5d1779900f.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/FrancescoXX/4c-site/blob/main/docs/CODE_OF_CONDUCT.md)

**Comment by hirentimbadiya** [comment]
I'd love to work on this , can you assign me this @FrancescoXX , @money8203 , @eddiejaoude

**Comment by eddiejaoude** [comment]
@hirentimbadiya I am not a maintainer on this repo, so I cannot help

Some tips that might help though
- look at the issue labels, this issue is still awaiting `status: awaiting triage` by the maintainers and is not ready for dev, so it cannot be assigned
- don't take people if not relevant to them, this creates noise not value, the repo maintainers will get notified of your comment, so tagging the maintainers is not required

**Comment by hirentimbadiya** [comment]
> @hirentimbadiya I am not a maintainer on this repo, so I cannot help
> 
> Some tips that might help though
> 
> * look at the issue labels, this issue is still awaiting `status: awaiting triage` by the maintainers and is not ready for dev, so it cannot be assigned
> * don't take people if not relevant to them, this creates noise not value, the repo maintainers will get notified of your comment, so tagging the maintainers is not required

thanks Eddie for helping and giving advise!!

**Comment by eddiejaoude** [comment]
You are welcome 👍  we are all always learning, so we learn together and other people can also learn from the discussion

**Comment by Vijaykv5** [comment]
This issue has been fixed in #477 
Thank you all!
